### PR TITLE
Update members.yml

### PR DESCRIPTION
**Pull request by leroybanks**
I am ITM 352 Rick Kazman section.

### CODE REVIEW

**Comment by dport96** [comment]
Hi Leroy, it seems that you forgot to put a "_ " in front of your entry in memebers.yml. Please fix this and request a new Pull

**Comment by leroybanks** [comment]
Good evening sir,

Thank you for letting me know. I just submitted my MIS portfolio again and
I send my pull request as well. Please let me know if you got the request
sir.

Very respectfully,

Leroy Banks

**Comment by leroybanks** [comment]
Sir,

Im #80 and #81. I did it twice just in case sir.

Very respectfully,

Leroy

**Comment by dport96** [comment]
Lol, totally unnecessary! The entire reason for using GitHub is so we don't
have to send emails and multiple requests!

**Comment by leroybanks** [comment]
Yes sir, sounds good. Thank you. I really appreciate it. Just to clarify, am I good to go?

**Pull request closed without merging**
