### PR TITLE
Update members.yml

### PR DESCRIPTION
**Pull request by aamarcon**
I am a student and I added my name to fall 2022 to add my portfolio to the MIS portfolios. starts with aamarcon.

### CODE REVIEW

**Comment by dport96** [comment]
Hey! I don't think you want 
  - aamarcon.github.io/aamarcon-github.io/
as the link to your portfolio. Try 
  - aamarcon.github.io

Please update and submit another Pull request

**Comment by aamarcon** [comment]
I am not sure how I can change the URL to be that.

Is there a way you can direct me in the right direction?

thank you

**Comment by aamarcon** [comment]
Please disregard the last email. I have fixed the problem and will be
sending a pull request.

thank you

**Comment by dport96** [comment]
Excellent!

**Pull request closed without merging**
