### PR TITLE
Update members.yml

### PR DESCRIPTION
**Pull request by betteagiacomelli**

### CODE REVIEW

**Comment by dport96** [comment]
This is not the correct way to add your portfolio URL to the members.yml file. Please fix and resubmit a pull request.

**Comment by betteagiacomelli** [comment]
Do I have to start over?

**Comment by dport96** [comment]
No, just edit the members.yml file with the correct way to add your URL.
Look at the others as an example of what you are supposed to do. Then
commit and make a pull request.

**Comment by betteagiacomelli** [comment]
[image: image.png]
I'm not sure if it worked. I didn't get an email confirmation that the
branches have been merged.

**Pull request closed without merging**
